import path from "node:path";
import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";

export type EnvFileWriteResult = {
  path: string;
  updatedNames: string[];
};

export function isValidEnvName(input: string | undefined): input is string {
  return typeof input === "string" && /^[A-Za-z_][A-Za-z0-9_]*$/.test(input);
}

export function getEnvFilePath(configPath: string): string {
  return path.join(path.dirname(configPath), "env");
}

function parseEnvValue(rawValue: string): string {
  const trimmed = rawValue.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return trimmed
      .slice(1, -1)
      .replace(/\\"/g, '"')
      .replace(/\\n/g, "\n")
      .replace(/\\\\/g, "\\");
  }

  if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1).replace(/'\\''/g, "'");
  }

  return trimmed;
}

function parseEnvFile(contents: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const match = /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/.exec(trimmed);
    if (!match) {
      continue;
    }
    values.set(match[1], parseEnvValue(match[2]));
  }
  return values;
}

function serializeEnvValue(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

async function readEnvValues(envPath: string): Promise<Map<string, string>> {
  try {
    return parseEnvFile(await readFile(envPath, "utf8"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return new Map();
    }
    throw error;
  }
}

export async function loadEnvFile(configPath: string): Promise<void> {
  const values = await readEnvValues(getEnvFilePath(configPath));
  for (const [name, value] of values) {
    process.env[name] ??= value;
  }
}

export async function writeEnvValues(configPath: string, updates: Record<string, string>): Promise<EnvFileWriteResult | null> {
  const entries = Object.entries(updates).filter(([name, value]) => isValidEnvName(name) && value);
  if (entries.length === 0) {
    return null;
  }

  const envPath = getEnvFilePath(configPath);
  const values = await readEnvValues(envPath);
  const updatedNames: string[] = [];
  for (const [name, value] of entries) {
    values.set(name, value);
    process.env[name] = value;
    updatedNames.push(name);
  }

  const contents = [
    "# Generated by braincode setup. Keep this file private.",
    ...Array.from(values.entries()).map(([name, value]) => `${name}=${serializeEnvValue(value)}`),
    ""
  ].join("\n");

  await mkdir(path.dirname(envPath), { recursive: true });
  await writeFile(envPath, contents, { encoding: "utf8", mode: 0o600 });
  await chmod(envPath, 0o600);
  return {
    path: envPath,
    updatedNames
  };
}
